// src/data/advertisingBanners.ts
import { BannerOffer } from "../components/home/SalesBanner";

const DEFAULT_GRADIENT = "linear-gradient(90deg, #accbee 0%, #e7f0fd 100%)";

export const ADVERTISING_BANNERS: BannerOffer[] = [
  {
    id: 2001,
    name: "Be Part of Something Big – Join Salesnet Today!",
    discount: "100",
    is_percentage: false,
    promo_code: "Cheap",
    image: "/assets/img/home/banner/camera.png",
    gradient: DEFAULT_GRADIENT,
    link: "/auth/signup",
    effectiveImage: "/assets/img/home/banner/camera.png",
    effectiveGradient: DEFAULT_GRADIENT,
  },
  {
    id: 2002,
    name: "Enjoy Nigerian Delicacies – Egusi Soup 🍲",
    discount: "200",
    is_percentage: false,
    promo_code: "Secured",
    image: "/assets/img/home/banner/ekusi_soup.png",
    gradient: DEFAULT_GRADIENT,
    link: "/categories/food",
    effectiveImage: "/assets/img/home/banner/ekusi_soup.png",
    effectiveGradient: DEFAULT_GRADIENT,
  },
  {
    id: 2003,
    name: "Furnish Your Home with Quality Furniture 🛋️",
    discount: "400",
    is_percentage: false,
    promo_code: "Faster",
    image: "/assets/img/home/banner/furniture.png",
    gradient: DEFAULT_GRADIENT,
    link: "/categories/furniture",
    effectiveImage: "/assets/img/home/banner/furniture.png",
    effectiveGradient: DEFAULT_GRADIENT,
  },
  {
    id: 2004,
    name: "Seasonal Fashion – Fall Collection 🍂",
    discount: "0",
    is_percentage: false,
    promo_code: "Top Rated Quality",
    image: "/assets/img/home/banner/fall_season.png",
    gradient: DEFAULT_GRADIENT,
    link: "/categories/fashion",
    effectiveImage: "/assets/img/home/banner/fall_season.png",
    effectiveGradient: DEFAULT_GRADIENT,
  },
  {
    id: 2005,
    name: "Step Up with Stylish Sneakers 👟",
    discount: "500",
    is_percentage: false,
    promo_code: "Fine You",
    image: "/assets/img/home/banner/sneakers.png",
    gradient: DEFAULT_GRADIENT,
    link: "/categories/shoes",
    effectiveImage: "/assets/img/home/banner/sneakers.png",
    effectiveGradient: DEFAULT_GRADIENT,
  },
  {
    id: 2006,
    name: "Handmade Knitted Bag – Unique & Elegant 👜",
    discount: "200",
    is_percentage: false,
    promo_code: "Hand-Made",
    image: "/assets/img/home/banner/knitted_bag.png",
    gradient: DEFAULT_GRADIENT,
    link: "/categories/fashion",
    effectiveImage: "/assets/img/home/banner/knitted_bag.png",
    effectiveGradient: DEFAULT_GRADIENT,
  },
  {
    id: 2007,
    name: "Taste the Classic – Jollof Rice 🍛",
    discount: "300",
    is_percentage: false,
    promo_code: "Classic Taste",
    image: "/assets/img/home/banner/jollof.png",
    gradient: DEFAULT_GRADIENT,
    link: "/categories/food",
    effectiveImage: "/assets/img/home/banner/jollof.png",
    effectiveGradient: DEFAULT_GRADIENT,
  },
  {
    id: 2008,
    name: "Jollof with Fried Plantain – A Nigerian Favourite 🍽️",
    discount: "300",
    is_percentage: false,
    promo_code: "Quality Nutrition",
    image: "/assets/img/home/banner/jollof_and_fried.png",
    gradient: DEFAULT_GRADIENT,
    link: "/categories/food",
    effectiveImage: "/assets/img/home/banner/jollof_and_fried.png",
    effectiveGradient: DEFAULT_GRADIENT,
  },
  {
    id: 2009,
    name: "Sweet Party Jollof – Perfect for Every Occasion 🎉",
    discount: "100",
    is_percentage: false,
    promo_code: "",
    image: "/assets/img/home/banner/jollof_sweet.png",
    gradient: DEFAULT_GRADIENT,
    link: "/categories/food",
    effectiveImage: "/assets/img/home/banner/jollof_sweet.png",
    effectiveGradient: DEFAULT_GRADIENT,
  },
  {
    id: 2010,
    name: "Afang Soup – A Taste of the South 🌿",
    discount: "300",
    is_percentage: false,
    promo_code: "Afang-Soup-Of-Life",
    image: "/assets/img/home/banner/afang_soup.png",
    gradient: DEFAULT_GRADIENT,
    link: "/categories/food",
    effectiveImage: "/assets/img/home/banner/afang_soup.png",
    effectiveGradient: DEFAULT_GRADIENT,
  },
  {
    id: 2011,
    name: "Okufe Goat Meat – Rich & Delicious 🍖",
    discount: "300",
    is_percentage: false,
    promo_code: "",
    image: "/assets/img/home/banner/okufe_goat_meat.png",
    gradient: DEFAULT_GRADIENT,
    link: "/categories/food",
    effectiveImage: "/assets/img/home/banner/okufe_goat_meat.png",
    effectiveGradient: DEFAULT_GRADIENT,
  },
];
